### PR TITLE
Add auth to study details view.

### PR DESCRIPTION
**Pull request by jezdez**
And some other minor things.

### CODE REVIEW

**Comment by jezdez** [comment]
@robhudson r?

**Comment by robhudson** [comment]
That was fast. This looks great.

If you haven't already, can you review the tests? This was obviously missing a check in the tests that this endpoint required auth (or the test provided the auth but the view never used it).

**Comment by jezdez** [comment]
@robhudson Yep, added a test for the auth stuff, at least via the session backend. The JWT backend is untested at the moment.

**Comment by robhudson** [comment]
Great changes. r+

**Pull request merged**
